// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfXv6LYlyiNlwpjg941hLpfG4xTI6xUUg',
    appId: '1:198341140377:web:3bd408492a1868432bfd08',
    messagingSenderId: '198341140377',
    projectId: 'mirror-original',
    authDomain: 'mirror-original.firebaseapp.com',
    storageBucket: 'mirror-original.firebasestorage.app',
    measurementId: 'G-F5VZEZV7ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6rIFyoVK3Gg3PINLOCxbAibmvRX6FFZ8',
    appId: '1:198341140377:android:569948331e4b3c882bfd08',
    messagingSenderId: '198341140377',
    projectId: 'mirror-original',
    storageBucket: 'mirror-original.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQOT82E4umzPACsLwl4X4FeGW_lvvalk',
    appId: '1:198341140377:ios:e38dc347704da8c82bfd08',
    messagingSenderId: '198341140377',
    projectId: 'mirror-original',
    storageBucket: 'mirror-original.firebasestorage.app',
    iosBundleId: 'com.example.mirrorOriginal',
  );
}
